branch-defaults:
  default:
    environment: x23340312-env
  master:
    environment: my-env
    group_suffix: null
environment-defaults:
  x23340312-env:
    branch: null
    repository: null
global:
  application_name: x23340312
  default_ec2_keyname: null
  default_platform: Python 3.9 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
